artist_name: "Noni Boyle"
contact_email: "ncboyle2@gmail.com"
intro_title: "Studio Sale"
intro_subtitle: "Various works: 2007-2024"


location: "9527 100a St"
date: "October 18"
time: "12:00PM-4:00PM"
note:  "contact: ncboyle2@gmail.com"
